name: Data Refresh

on: 
  push:
    branches: [main, master]
  schedule:  
    - cron: '0 22 * * *'

jobs:
  update-data:
    runs-on: ubuntu-latest 
    permissions:
      contents: write
      actions: write
      pages: write

    container: 
      image: mgaloto/scrapppython:02
    steps:
    - name: checkout_repo
      uses: actions/checkout@v3
      with: 
        ref: 'main'
    - name: Ejecutar script
      run: python etl.py
      env:
        EMAIL: ${{ secrets.EMAIL }}
        PSS: ${{ secrets.PSS }}
    - name: Commit
      run: bash ./bash/commit.sh "MGaloto" "maxigaloto@hotmail.com"

